# playbooks/setup-pxe-server.yml
---
- name: Configure PXE boot server
  hosts: pxe_server
  become: true

  vars:
    # using the vagrant shared folder so that survives a vagrant destroy and vagrant up cycle
    sharedisos: /vagrant/www/sharedisos
    http_root: /vagrant/www
    tftp_root: /srv/tftp

    ubuntu_iso_url: https://releases.ubuntu.com/resolute/ubuntu-26.04-live-server-amd64.iso
    ubuntu_iso_name: ubuntu-26.04-live-server-amd64.iso
    
    dnsmasq_interface: eth2
    dnsmasq_domain: lab.example.com
    dnsmasq_dhcp_range_start: 192.168.20.210
    dnsmasq_dhcp_range_end: 192.168.20.230
    dnsmasq_dhcp_lease_time: 1h
    dnsmasq_gateway:   192.168.20.200
    dnsmasq_dns_servers:
      - 194.81.151.70
    #  - 8.8.8.8


  roles:
    - dnsmasq-config
    - pxeboot

  handlers:
    - name: restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted

    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        