--- # Creating an EC2 Instance 

- name: Creating an EC2 Instance with ansible cli

  hosts: localhost

  vars:
    region: eu-west-2
    instance_type: t3.micro
    # AlmaLinux OS 10 (x86_64) AlmaLinux OS Foundation 
    ami: ami-041f62d0737a0fbd1
    key_name: ansible-demo1
    vpc_name: ansible-vpc-test
    cidr_block: "10.10.0.0/16"
    cidr: "10.10.0.0/24"

#    aws_access_key: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY') }}"
#    aws_secret_key: "{{ lookup('ansible.builtin.env', 'AWS_SECRET_KEY') }}" 

  vars_files:
    - ./vault.yml

  tasks:

   - name: delete ec2 instances
     amazon.aws.ec2_instance:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      aws_region: "{{ region }}"
      state: absent
      filters:
        tag:usage: ansible-simple-1
        
        
   - name: Grab VPC details
     amazon.aws.ec2_vpc_net_info:
       aws_region: "{{ region }}"
       filters:
          tag:usage: ansible-simple-1
     register: all_vpcs
     
   - name: remove subnets and route tables from VPC
     local_action:
         module: ec2_vpc
         vpc_id: "{{ item.vpc_id }}"
         region: "{{ region }}"
         state: present
         resource_tags: "{}"
         subnets: []
         internet_gateway: False
         route_tables: []
         wait: yes
     loop: "{{ all_vpcs.vpcs }}"
     when: item.is-default != true
      
      
#   - name: Delete Security Groups in VPC {{ all_vpcs.vpcs[0].vpc_id }} by ID
#     amazon.aws.ec2_group:
#         region: "{{ ec2_region }}"
#         group_id: "{{ item.group_id }}"
#         state: absent
#     loop: "{{ all_sg.security_groups }}"
#     when: item.group_name != "default"
        
#   - name: delete aws security group
#     amazon.aws.ec2_security_group:
#       aws_access_key: "{{ aws_access_key }}"
#       aws_secret_key: "{{ aws_secret_key }}"
#       aws_region: "{{ region }}"
#       state: absent
#       filters:
#        tag:usage: ansible-simple-1
#             
#   - name: delete aws subnets
#     amazon.aws.ec2_vpc_subnet:
#      aws_access_key: "{{ aws_access_key }}"
#      aws_secret_key: "{{ aws_secret_key }}"
#      aws_region: "{{ region }}"
#      state: absent
#      filters:
#        tag:usage: ansible-simple-1
#   
#   - name: delete aws vpc 
#     amazon.aws.ec2_vpc_net:
#      aws_access_key: "{{ aws_access_key }}"
#      aws_secret_key: "{{ aws_secret_key }}"
#      aws_region: "{{ region }}"
#      state: absent
#      filters:
#        tag:usage: ansible-simple-1
   
   
   
   
   
   
   
   
   