{
 "title": "radio-main-1",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodeLabel",
    "query": "SELECT nodelabel FROM node where location = '$nodelocation'"
   },
   {
    "name": "nodelocation",
    "label": "location",
    "query": "SELECT DISTINCT node.location FROM assets INNER JOIN node ON assets.nodeid = node.nodeid  WHERE displaycategory = '$customer';"
   },
   {
    "name": "customer",
    "label": "customer",
    "query": "SELECT  DISTINCT displayCategory FROM assets"
   }
  ]
 },
 "panels": [
  { "title": "Select Site on Geomap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GEOMAP",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (node.location) node.location AS location, latitude, longitude FROM assets INNER JOIN node ON assets.nodeid = node.nodeid  WHERE latitude IS NOT NULL; "
    }
   ]
  },
  { "title": "Selected Site $nodelocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "devices in site $nodelocation",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT  node.nodelabel,assets.category FROM assets INNER JOIN node ON assets.nodeid = node.nodeid  WHERE node.location = '${nodelocation}'\r\n"
    }
   ]
  },
  {
   "title": "Devices with alarms on site $nodelocation",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (node.nodeid)  node.nodelabel, assets.category, a.severity,  ( CASE a.severity WHEN 7 THEN 'Critical' WHEN 6 THEN 'Major'   WHEN 5 THEN 'Minor'  WHEN 4 THEN 'Warning' WHEN 3 THEN 'Cleared' ELSE 'Indeterminate' END ) AS severityLabel\r\nFROM node LEFT JOIN assets ON assets.nodeid = node.nodeid  LEFT JOIN alarms a ON a.nodeid = node.nodeid \r\nWHERE node.location = '${nodelocation}' AND  a.severity= (\r\n    SELECT MAX(severity)\r\n    FROM alarms\r\n    WHERE nodeid = a.nodeid\r\n) ;\r\n"
    }
   ]
  },
  { "title": "Alarm Tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "alarms on $nodeLabel",
   "type": "opennms-alarm-table-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "clauses": [
      {
       "attribute": {
        "label": "Node Label",
        "type": { "id": "STRING", "label": "string" },
        "value": {
         "id": "node.label",
         "label": "Node Label",
         "name": "Node: Label",
         "orderBy": true,
         "type": { "id": "STRING", "label": "string" }
        }
       },
       "comparator": { "label": "EQ", "value": { "id": 1, "label": "EQ" } },
       "comparedString": "$nodeLabel",
       "comparedValue": {},
       "nestingType": 0,
       "type": 2
      }
     ],
     "filter": {
      "clauses": [
       {
        "operator": { "id": 1, "label": "AND" },
        "restriction": { "attribute": "node.label", "comparator": { "id": 1, "label": "EQ" }, "value": "$nodeLabel" }
       }
      ],
      "limit": 10,
      "orderBy": []
     },
     "selectType": { "label": "Alarms" }
    }
   ]
  },
  {
   "title": "All Alarms",
   "type": "opennms-alarm-table-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "clauses": [
      {
       "attribute": {},
       "comparator": { "label": "EQ", "value": { "id": 1, "label": "EQ" } },
       "comparedString": "",
       "comparedValue": {},
       "nestingType": 0,
       "type": 2
      }
     ],
     "filter": {
      "clauses": [
       { "operator": { "id": 1, "label": "AND" }, "restriction": { "comparator": { "id": 1, "label": "EQ" } } }
      ],
      "limit": 10,
      "orderBy": []
     },
     "selectType": { "label": "Alarms" }
    }
   ]
  }
 ]
}