# inventories/bare-metal/hosts.yml

all:
  children:
    bare_metal:
      hosts:
        bm-web-01:
          ansible_host: 10.0.1.10
          ipmi_host: 10.0.100.10
          ipmi_user: admin
          ipmi_password: "{{ vault_ipmi_password }}"
          mac_address: "aa:bb:cc:dd:ee:01"
          server_role: webserver
          raid_config: raid1
          os_version: ubuntu-2204
        bm-db-01:
          ansible_host: 10.0.2.10
          ipmi_host: 10.0.100.20
          ipmi_user: admin
          ipmi_password: "{{ vault_ipmi_password }}"
          mac_address: "aa:bb:cc:dd:ee:02"
          server_role: database
          raid_config: raid1
          os_version: ubuntu-2204
          