---
http-url: "https://172.236.28.206/opennms"
broker-url: "failover:tcp://172.236.28.206:61616"
id: "minion-remote-pi-01"
location: "ftwidley1"

karaf:
  shell:
    ssh:
      host: "0.0.0.0"

netmgt:
  syslog:
    syslog.listen.interface: "0.0.0.0"
    syslog.listen.port: 1514

  traps:
    trapd.listen.interface: "0.0.0.0"
    trapd.listen.port: 1162
