---
#------------------------------------------------------------------------------
#
# Create a simple AWS instance:
# 1. Create SSH Key Pair
# 2. Create VPC
# 3. Create Internet Gateway
# 4. Create Subnet
# 5. Create Route Table
# 6. Create Security Group
# 7. Create EC2 Instance
#
# Assumes AWS_* environment variables for task authentication:
#   export AWS_REGION='us-west-1'
#   export AWS_ACCESS_KEY='AKIAIOSF/EXAMPLE+KEY'
#   export AWS_SECRET_KEY='wJalrXUtnFEMI/K7MDENG/bPxRfi/EXAMPLE+KEY'
#
# Run with `ansible-playbook playbook.yaml`
#
# Connect with `ssh -i ./AWS_EC2_Instance_Test.private_key.pem ec2-user@hostname`
#
# For more AMI IDs for other images and in different regions, see
# <https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html>
#
#------------------------------------------------------------------------------

- name: AWS EC2 Instance Playbook
  hosts: localhost
  connection: local
  gather_facts: true   # required for `ansible_date_time`
#  vars:
#    project_name: AWS_EC2_Instance_Test
#    ami_id: ami-041f62d0737a0fbd1 #alma 10  # ami-04b6c97b14c54de18   # Amazon Linux 2 AMI (HVM), SSD Volume Type
#    instance_type: t2.micro
#    vpc_cidr: 172.31.0.0/16
#    sub_cidr: 172.31.1.0/24

  tasks:


  - name: Show Playbook Options
    ansible.builtin.debug:
      msg:
      - "project_name: {{ project_name }}"
      - "aws_region: {{ aws_region }}"


  - name: Start all EC2 instances in Project "{{ project_name }}"
    community.aws.ec2_instance:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       region: "{{ aws_region }}"
       state: running
 #      network:
 #         assign_public_ip: true
       filters:
         instance-state-name: stopped
         "tag:Project": "{{ project_name }}"

       wait: true
    register: startec2

  - name: Show startec2
    ansible.builtin.debug: var=startec2
    
  - name: get-facts
    ec2_instance_info:
      region: "{{ aws_region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      filters:
        "tag:Name": "{{ host_name1 }}"
        "tag:Project": "{{ project_name }}"
    register: ec2
    
  - name: Show ec2 facts
    debug: var="ec2.instances[0].public_ip_address"
    
  - name: List all hosted zones
    amazon.aws.route53_info:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       query: hosted_zone
    register: hosted_zones
    
  - name: Show hosted zones    
    ansible.builtin.debug: var=hosted_zones
    
  # Create an A record pointing to a specific IP
  # Note: If the record already exists, it will be updated with the new IP address.
  # todo remove the record on project termination
  - name: Create A record for web server
    amazon.aws.route53:
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       zone:  "{{ hosted_zone }}"
       record: "{{ host_name1 }}.noc.{{deployment}}.{{ hosted_zone }}"
       type: A
       value: "{{ ec2.instances[0].public_ip_address }}"
       ttl: 300
       state: present
       overwrite: true
    register: route53_record
    
  - name: Show route53_record
    ansible.builtin.debug: var=route53_record   

  - name: Show SSH Commands for Instance
    ansible.builtin.debug:
      msg:
      - "ssh -i {{ lookup('env', 'HOME') }}/.ssh/{{ project_name }}.private_key.pem ec2-user@{{ ec2.instances[0].public_ip_address}}"
      - "ssh -i {{ lookup('env', 'HOME') }}/.ssh/{{ project_name }}.private_key.pem ec2-user@{{ ec2.instances[0].public_dns_name}}"
      - "ssh -i {{ lookup('env', 'HOME') }}/.ssh/{{ project_name }}.private_key.pem ec2-user@{{ host_name1 }}.noc.{{deployment}}.{{ hosted_zone }}"

...