---
- name: uninstall apache
  hosts: web
  become: yes
  
  pre_tasks:
  
     - name: Unlock SSH key "{{ ssh_key_file }}"
       shell: rm -f /tmp/ansible_add_ssh_run_pid; echo "$(sudo cat /home/ansible/.ssh/id_rsa)" | SSH_ASKPASS_REQUIRE=force  SSH_ASKPASS=/share/ssh-pass.sh ssh-add -
       delegate_to: 127.0.0.1
       become: no
       changed_when: no
       no_log: false
      
  roles:
    - uninstall-apache2

  post_tasks:
    # Optional, to remove the keys from the agent at the end:
    - name: Remove ssh keys
      command: ssh-add -D
      delegate_to: 127.0.0.1
      become: no
      changed_when: no
