# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # just the commands without the comments
  config.vm.define "alma10-base1" do |alma10-base1|
  
     alma10-base1.vm.box = "almalinux/10"
     alma10-base1.vm.box_version = "10.1.20260110"
     
     alma10-base1.vm.disk :disk, size: "50GB", primary: true
     
     # alma10-base1.vm.synced_folder ".", "/vagrant", disabled: true
     
     alma10-base1.vm.hostname = "alma10-base1"
  
     alma10-base1.vm.provider "virtualbox" do |vb|
        # Display the VirtualBox GUI when booting the machine
        vb.gui = true
  
        # Customize the amount of memory and cpu on the VM:
        vb.memory = "1024"
        vb.cpus = 2
        
        # set up second host only network (on windows)
        vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
        vb.customize ["modifyvm", :id, "--hostonlyadapter2", "VirtualBox Host-Only Ethernet Adapter"] #use systems network name here
        vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
        
     end
  
     #alma10-base1.vm.provision "shell", path: "provision.sh"
     
     # This shell provisioner will trigger a reboot
     #alma10-base1.vm.provision "shell", reboot: true, inline: "echo 'Rebooting now...'"
  
     # This runs AFTER the reboot
     #alma10-base1.vm.provision "shell", inline: "echo 'Machine is back up!'"
   
  end  # alma10-base1
  
  
  
end
