---

# Delete existing PXE boot menu files
- name: Get directory listing
  find:
    path: "{{ tftp_root }}/pxelinux.cfg/" 
    file_type: any
    hidden: yes
  register: directory_content_result
  
- name: debug pxeboot role
  debug:
     msg: "removing existing PXE boot menu files from {{ tftp_root }}/pxelinux.cfg/ directory content={{ directory_content_result.files | map(attribute='path') | list }}"

- name: Remove directory content
  file:
    path: "{{ item.path }}" 
    state: absent
  with_items: "{{ directory_content_result.files }}" 
  loop_control:
    label: "{{ item.path }}" 

- name: Create Default PXE menu which just boots local disk
  ansible.builtin.copy:
   dest: "{{ tftp_root }}/pxelinux.cfg/default"
   content: |
     DEFAULT menu.c32
     PROMPT 0
     TIMEOUT 100
     MENU TITLE PXE Boot Menu

     LABEL local
       MENU LABEL Boot from local disk
       LOCALBOOT 0
   mode: '0644'

- name: generate pxeboot ubuntu config
  include_tasks: pxebootubuntu.yml
  when: (hostvars[item].os_id | default('', true) | trim == 'ubuntu' ) and (hostvars[item].eth0_mac | default('', true) | trim !='')
  with_items: "{{ groups.all }}"
