---

- name: generate pxeboot ubuntu config
  include_tasks: pxebootubuntu.yml
  when: (hostvars[item].os_id | default('', true) | trim == 'ubuntu' ) and (hostvars[item].eth0_mac | default('', true) | trim !='')
  with_items: "{{ groups.all }}"
