---
- name: debug preparefiles-ubuntu
  debug:
     msg: "preparing download files for os_id={{sharedisos}}/{{hostvars[item].os_id | default('', true) | trim }} os_version_id= {{ hostvars[item].os_version_id | default('', true) | trim }} }}"
     
- name: check if iso file exists
  stat: 
    path: "{{sharedisos}}/{{hostvars[item].os_id | default('', true) | trim }}/{{ hostvars[item].os_version_id | default('', true) | trim }} }}/vmlinuz"
  register: download_vmlinuz_file_stat
     
- name: Download and unpack iso file if it does not exist
  when: download_vmlinuz_file_stat.stat.exists == false
  block:
       - name: downloading iso files
         debug:
             msg: "preparing download files for {{ubuntu_iso_url}}  Downloading the ISO can take a very long time"
             
       - name: test iso message
         debug:
             msg: "iso_name={{iso_name}} iso_url={{iso_url}} iso_file_path={{iso_file_path}} iso_mount_point={{iso_mount_point}}"
             
# doesnt work because of Rocky 9 ansible bug    
# • https://community.theforeman.org/t/managing-ubuntu-24-04-hosts-with-foreman-using-ansible-unable-to-use-multiple-modules-b-c-of-httpsconnection-init-got-an-unexpected-keyword-argument-cert-file/42017          
#       - name: Download ISO
#         ansible.builtin.get_url:
#            url: "{{ubuntu_iso_url}}"
#            dest: "{{iso_file_path}}"
#            # checksum: "sha256:https://example.com.sha256"
#            force: false # will not download if already exists

       - name: Download ISO
         ansible.builtin.shell: |
           wget -O "{{iso_file_path}}" "{{ubuntu_iso_url}}"
         args:
           creates: "{{iso_file_path}}"

       - name: Ensure mount point exists
         ansible.builtin.file:
           path: "{{iso_mount_point}}"
           state: directory
           mode: '0755'

       - name: Mount ISO file as a loop device
         ansible.posix.mount:
           path: "{{iso_mount_point}}"
           src: "{{iso_file_path}}"
           fstype: iso9660
           opts: loop,ro
           state: mounted

       - name: Ensure bootimages folder exists
         ansible.builtin.file:
           path: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/bootimages"
           state: directory
           mode: '0755'
           
       - name: Copy ubuntu kernel and initrd for PXE boot
         ansible.builtin.copy:
           # note casper folder is where the kernel and initrd are located in ubuntu iso
           src: "{{iso_mount_point}}/casper/{{ image_item }}"
           dest: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/bootimages/{{ image_item }}"
           remote_src: true
           mode: '0777'
         loop:
           - vmlinuz
           - initrd
         loop_control:
           loop_var: image_item 

       - name: Unmount ISO file on Linux
         ansible.posix.mount:
           path: "{{iso_mount_point}}"
           src: "{{iso_file_path}}"
           state: unmounted
  vars:
      os_id: "{{hostvars[item].os_id | default('', true) | trim }}"
      os_version_id: "{{ hostvars[item].os_version_id | default('', true) | trim }}"
      iso_name: "{{ operating_systems | json_query('[?contains(os_id, `ubuntu`) && contains(to_string(os_version_id), `26.04`)].iso_name | [0] ') }}"
      iso_url: "{{ operating_systems | json_query('[?contains(os_id, `ubuntu`) && contains(to_string(os_version_id), `26.04`)].iso_url | [0] ') }}"
     # iso_url: "{{ operating_systems | json_query(\"[?os_id==hostvars[`{{item}}`].os_id && os_version_id==hostvars[`{{item}}`].os_version_id].iso_url | [0]\") }}"
      iso_file_path: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/{{ubuntu_iso_name}}"
      iso_mount_point : /tmp/iso/{{os_id}}/{{os_version_id}}
      
      
      
      
      
      
- name: create pxe boot files for inventory
  block:

       - name: Create ftp directory
         ansible.builtin.file:
           path: "{{ tftp_root }}/{{ os_id }}/{{ os_version_id }}/bootimages"
           state: directory
           mode: '0755'

       # note must have unpacked iso first
       - name: Copy ubuntu kernel and initrd for PXE boot to tftp root
         ansible.builtin.copy:
           src: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/bootimages/{{ image_item }}"
           dest: "{{ tftp_root }}/{{os_id}}/{{os_version_id}}/bootimages/{{ image_item }}"
           remote_src: true
           mode: '0644'
         loop:
           - vmlinuz
           - initrd
         loop_control:
            loop_var: image_item 

       - name: Create config directory
         ansible.builtin.file:
           path: "{{sharedisos}}//{{os_id}}/{{os_version_id}}/conf/default"
           state: directory
           mode: '0755'

       - name: Copy config files
         ansible.builtin.copy:
           src: ../files//{{os_id}}/{{os_version_id}}/conf/default/{{ image_item }}
           dest: "{{sharedisos}}//{{os_id}}/{{os_version_id}}/conf/default/{{ image_item }}"
           mode: '0644'
         loop:
           - meta-data
           - network-config
           - user-data
           - vendor-data
         loop_control:
            loop_var: image_item 
         notify: restart nginx


       - name: debug pxebootubuntu.yml
         debug:
           msg: "generating pxeboot config for os_id={{hostvars[item].os_id | default('', true) | trim }} os_version_id= {{ hostvars[item].os_version_id | default('', true) | trim }} eth0_mac={{ hostvars[item].eth0_mac | default('', true) | trim }}"
          
       - name: Create Ubuntu pxe Mac specific PXE menu
         ansible.builtin.copy:
            dest: "{{ tftp_root }}/pxelinux.cfg/01-{{ hostvars[item].eth0_mac  | replace(':','-') | lower }}"
            content: |
              DEFAULT menu.c32
              PROMPT 0
              TIMEOUT 100
              MENU TITLE PXE Boot Menu for {{ item }} eth0_mac={{ hostvars[item].eth0_mac }}

              LABEL ubuntu
                MENU LABEL Install Ubuntu 24.04
                KERNEL /{{os_id}}/{{os_version_id}}/bootimages/vmlinuz
                INITRD /{{os_id}}/{{os_version_id}}/bootimages/initrd
                SYSAPPEND 3
                APPEND  url=http://{{ dnsmasq_gateway }}:8080/sharedisos//{{os_id}}/{{os_version_id}}/{{ubuntu_iso_name}} cloud-config-url=/dev/null autoinstall  ds=nocloud-net;s=http://{{ dnsmasq_gateway }}:8080/sharedisos//{{os_id}}/{{os_version_id}}/conf/default/ fsck.mode=skip
            
              LABEL local
                MENU LABEL Boot from local disk
                LOCALBOOT 0
            mode: '0644'

  vars:
      os_id: "{{hostvars[item].os_id | default('', true) | trim }}"
      os_version_id: "{{ hostvars[item].os_version_id | default('', true) | trim }}"
      iso_file_path: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/{{ubuntu_iso_name}}"
      iso_mount_point : /tmp/iso/{{os_id}}/{{os_version_id}}

     