---
- name: debug preparefiles-ubuntu
  debug:
     msg: "peparing download files for os_id={{sharedisos}}/{{hostvars[item].os_id | default('', true) | trim }} os_version_id= {{ hostvars[item].os_version_id | default('', true) | trim }} }}"
     
- name: check if iso file exists
  stat: 
    path: "{{sharedisos}}/{{hostvars[item].os_id | default('', true) | trim }}/{{ hostvars[item].os_version_id | default('', true) | trim }} }}/{{ubuntu_iso_name}}"
  register: download_iso_file_stat
     
- name: Download and unpack iso file if it does not exist
  when: download_iso_file_stat.stat.exists == false
  block:
       - name: downloading iso files
         debug:
             msg: "peparing download files for {{ubuntu_iso_url}}"
             
#       - name: Download ISO
#         ansible.builtin.get_url:
#            url: "{{ubuntu_iso_url}}"
#            dest: "{{iso-file-path}}"
#            # checksum: "sha256:https://example.com.sha256"
#            force: false # will not download if already exists

       - name: Ensure mount point exists
         ansible.builtin.file:
           path: /tmp/iso/ubuntu
           state: directory
           mode: '0755'

       - name: Mount ISO file as a loop device
         ansible.posix.mount:
           path: "{{iso-mount-point}}"
           src: "{{iso-file-path}}"
           fstype: iso9660
           opts: loop,ro
           state: mounted

       - name: Ensure bootimages folder exists
         ansible.builtin.file:
           path: "{{boot-images-path}}"
           state: directory
           mode: '0755'
           
       - name: Copy ubuntu kernel and initrd for PXE boot
         ansible.builtin.copy:
           # note casper folder is where the kernel and initrd are located in ubuntu iso
           src: "{{iso-mount-point}}/casper/{{ image_item }}"
           dest: "{{boot-images-path}}/{{ image_item }}"
           remote_src: true
           mode: '0777'
         loop:
           - vmlinuz
           - initrd.img
         loop_control:
           loop_var: image_item # Custom name prevents collisions

       - name: Unmount ISO file on Linux
         ansible.posix.mount:
           path: "{{iso-mount-point}}"
           src: "{{iso-file-path}}"
           state: unmounted
  vars:
      os-id: "{{hostvars[item].os_id | default('', true) | trim }}"
      os-version-id: "{{ hostvars[image_item].os_version_id | default('', true) | trim }}"
      iso-file-path: "{{sharedisos}}/{{os-id}}/{{os-version-id}}/{{ubuntu_iso_name}}"
      iso-mount-point : /tmp/iso/{{os-id}}/{{os-version-id}}
      boot-images-path: "{{sharedisos}}/{{os-id}}/{{os-version-id}}/bootimages"
          
 # note must have unpacked iso here
- name: Copy ubuntu kernel and initrd for PXE boot to tftp root
  ansible.builtin.copy:
    src: "{{sharedisos}}/ubuntu/{{ hostvars[image_item ].os_version_id | default('', true) | trim }} }}/bootimages/{{ item }}"
    dest: "{{ ubuntu_root }}/{{ image_item }}"
    remote_src: true
    mode: '0644'
  loop:
    - vmlinuz
    - initrd.img
  loop_control:
     loop_var: image_item # Custom name prevents collisions

- name: Create config directory
  ansible.builtin.file:
    path: "/vagrant/sharedisos/conf/default"
    state: directory
    mode: '0755'

- name: Copy config files
  ansible.builtin.copy:
    src: ../files/conf/default/{{ image_item }}
    dest: "/vagrant/sharedisos/conf/default/{{ image_item }}"
    mode: '0644'
  loop:
    - meta-data
    - network-config
    - user-data
    - vendor-data
  loop_control:
     loop_var: image_item # Custom name prevents collisions


- name: debug pxebootubuntu.yml
  debug:
    msg: "generating pxeboot config for os_id=ubuntu os_version_id= {{ hostvars[item].os_version_id | default('', true) | trim }} eth0_mac={{ hostvars[item].eth0_mac | default('', true) | trim }}"
          
- name: Create Ubuntu pxe Mac specific PXE menu
  ansible.builtin.copy:
     dest: "{{ tftp_root }}/pxelinux.cfg/01-{{ hostvars[item].eth0_mac  | replace(':','-') | lower }}"
     content: |
       DEFAULT menu.c32
       PROMPT 0
       TIMEOUT 100
       MENU TITLE PXE Boot Menu for {{ item }} eth0_mac={{ hostvars[item].eth0_mac }}

       LABEL ubuntu
         MENU LABEL Install Ubuntu 24.04
         KERNEL ubuntu/vmlinuz
         INITRD ubuntu/initrd.img
         SYSAPPEND 3
         APPEND  url=http://{{ dnsmasq_gateway }}:8080/sharedisos/{{ubuntu_iso_name}} cloud-config-url=/dev/null autoinstall  ds=nocloud-net;s=http://{{ dnsmasq_gateway }}:8080/sharedisos/conf/default/ fsck.mode=skip
            
       LABEL local
         MENU LABEL Boot from local disk
         LOCALBOOT 0
     mode: '0644'
