---
- name: debug preparefiles-debian
  debug:
     msg: "preparing download files for os_id={{sharedisos}}/{{hostvars[item].os_id | default('', true) | trim }} os_version_id= {{ hostvars[item].os_version_id | default('', true) | trim }} }}"
     
#- name: check if iso file exists
#  stat: 
#    path: "{{sharedisos}}/{{hostvars[item].os_id | default('', true) | trim }}/{{ hostvars[item].os_version_id | default('', true) | trim }} }}/vmlinuz"
#  register: download_vmlinuz_file_stat
     
- name: Download and unpack iso file if it does not exist
  # when: download_vmlinuz_file_stat.stat.exists == false
  run_once: true
  block:
       - name: downloading iso files
         debug:
             msg: "preparing download files for  iso_url={{iso_url}} iso_name={{iso_name}} iso_file_path={{iso_file_path}} iso_mount_point={{iso_mount_point}}  pxe_installer_url={{pxe_installer_url}} Downloading the ISO can take a very long time"

       - name: Ensure bootimages folder exists
         ansible.builtin.file:
           path: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/bootimages"
           state: directory
           mode: '0755'
           
       - name: Ensure directory for ISO file exists
         ansible.builtin.file:
           path: "{{iso_directory}}"
           state: directory
           mode: '0755'

       - name: Download ISO
         ansible.builtin.shell: |
           wget -O "{{iso_file_path}}" "{{iso_url}}"
         args:
           creates: "{{iso_file_path}}"
           
       - name: Ensure mount point exists
         ansible.builtin.file:
           path: "{{iso_mount_point}}"
           state: directory
           mode: '0755'

       - name: Mount ISO file as a loop device
         ansible.posix.mount:
           path: "{{iso_mount_point}}"
           src: "{{iso_file_path}}"
           fstype: iso9660
           opts: loop,ro
           state: mounted
           
       - name: Copy debian kernel and initrd for PXE boot
         ansible.builtin.copy:
           # note install.amd folder is where the kernel and initrd are located in debian iso
           src: "{{iso_mount_point}}/install.amd/{{ image_item }}"
           dest: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/bootimages/{{ image_item }}"
           remote_src: true
           mode: '0777'
         loop:
           - vmlinuz
           - initrd.gz
         loop_control:
           loop_var: image_item 
           
       - name: Ensure NFS Server folder exists
         ansible.builtin.file:
           path: "{{nfs_root}}/{{os_id}}/{{os_version_id}}"
           state: directory
           mode: '0755'
           
       # only rsync if /boot doesnt already exist
       - name: rsync iso to NFS Server folder
         ansible.builtin.shell: |
           rsync -av "{{iso_mount_point}}/" "{{nfs_root}}/{{os_id}}/{{os_version_id}}/"
         args:
           creates: "{{nfs_root}}/{{os_id}}/{{os_version_id}}/boot"

       - name: Unmount ISO file on Linux
         ansible.posix.mount:
           path: "{{iso_mount_point}}"
           src: "{{iso_file_path}}"
           state: unmounted
           
       - name: Ensure net bootimages folder exists
         ansible.builtin.file:
           path: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/netbootimages"
           state: directory
           mode: '0755'
           
       - name: Download PXE installer url
         ansible.builtin.shell: |
           wget -O "{{pxe_installer_filepath}}" "{{pxe_installer_url}}"
           rm -rf /tmp/pxe_installer_unpack
           mkdir -p /tmp/pxe_installer_unpack
           tar -xvzf "{{pxe_installer_filepath}}" -C /tmp/pxe_installer_unpack
         args:
           creates: "{{pxe_installer_filepath}}"
           
       - name: Copy netboot debian kernel and initrd for PXE boot
         ansible.builtin.copy:
           src: "/tmp/pxe_installer_unpack/debian-installer/amd64/{{ image_item }}"
           dest: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/netbootimages/{{ image_item }}"
           remote_src: true
           mode: '0777'
         loop:
           - linux
           - initrd.gz
         loop_control:
           loop_var: image_item 

  vars:
      os_id: "{{hostvars[item].os_id | default('', true) | trim }}"
      os_version_id: "{{ hostvars[item].os_version_id | default('', true) | trim }}"
      iso_name: "{{ operating_systems | selectattr('os_id', 'search', os_id)  | selectattr('os_version_id', 'equalto', os_version_id) | map(attribute='iso_name') | first }}"
      iso_url: "{{ operating_systems | selectattr('os_id', 'search', os_id)   | selectattr('os_version_id', 'equalto', os_version_id) | map(attribute='iso_url') | first }}"
      iso_file_path: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/{{iso_name}}"
      iso_directory: "{{sharedisos}}/{{os_id}}/{{os_version_id}}"
      iso_mount_point : /tmp/iso/{{os_id}}/{{os_version_id}}
      pxe_installer_filepath: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/netboot.tar.gz"
      pxe_installer_url: "{{ operating_systems | selectattr('os_id', 'search', os_id)   | selectattr('os_version_id', 'equalto', os_version_id) | map(attribute='pxe_installer_url') | first }}"

      
- name: create pxe boot files for inventory
  block:

       - name: Create tftp boot images directory
         ansible.builtin.file:
           path: "{{ tftp_root }}/{{ os_id }}/{{ os_version_id }}/bootimages"
           state: directory
           mode: '0755'
           
       - name: Create tftp isos directory
         ansible.builtin.file:
           path: "{{ tftp_root }}/{{ os_id }}/{{ os_version_id }}/isos"
           state: directory
           mode: '0755'

       - name: Copy debian iso to tftp root
         ansible.builtin.copy:
           src: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/{{iso_name}}"
           dest: "{{ tftp_root }}/{{os_id}}/{{os_version_id}}/isos/{{iso_name}}"
           remote_src: true
           mode: '0644'

       - name: Copy debian kernel and initrd for PXE boot to tftp root
         ansible.builtin.copy:
           src: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/bootimages/{{ image_item }}"
           dest: "{{ tftp_root }}/{{os_id}}/{{os_version_id}}/bootimages/{{ image_item }}"
           remote_src: true
           mode: '0644'
         loop:
           - vmlinuz
           - initrd.gz
         loop_control:
            loop_var: image_item 


       - name: Create tftp netbootimages directory
         ansible.builtin.file:
           path: "{{ tftp_root }}/{{ os_id }}/{{ os_version_id }}/netbootimages"
           state: directory
           mode: '0755'
           
       - name: Copy netboot debian kernel and initrd for PXE boot to tftp root
         ansible.builtin.copy:
           src: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/netbootimages/{{ image_item }}"
           dest: "{{ tftp_root }}/{{os_id}}/{{os_version_id}}/netbootimages/{{ image_item }}"
           remote_src: true
           mode: '0644'
         loop:
           - linux
           - initrd.gz
         loop_control:
            loop_var: image_item 

       - name: Create config directory
         ansible.builtin.file:
           path: "{{sharedisos}}//{{os_id}}/{{os_version_id}}/conf/default"
           state: directory
           mode: '0755'

       - name: Copy config template files
         ansible.builtin.template:
           src: ../files//{{os_id}}/{{os_version_id}}/conf/default/{{ image_item }}
           dest: "{{sharedisos}}//{{os_id}}/{{os_version_id}}/conf/default/{{ image_item }}"
           mode: '0644'
         loop:
           - preseed.conf
         loop_control:
            loop_var: image_item 
         notify: restart nginx


       - name: debug pxebootdebian.yml
         debug:
           msg: "generating pxeboot config for os_id={{hostvars[item].os_id | default('', true) | trim }} os_version_id= {{ hostvars[item].os_version_id | default('', true) | trim }} eth0_mac={{ hostvars[item].eth0_mac | default('', true) | trim }}"
          
       - name: Create debian pxe MAC address specific PXE menu
         ansible.builtin.copy:
            dest: "{{ tftp_root }}/pxelinux.cfg/01-{{ hostvars[item].eth0_mac  | replace(':','-') | lower }}"
            content: |
              DEFAULT menu.c32
              PROMPT 0
              TIMEOUT 100
              MENU TITLE PXE Boot Menu for {{ item }} eth0_mac={{ hostvars[item].eth0_mac }}
              
              LABEL {{os_id}} netboot pressed install (works)
                MENU LABEL Install {{os_id}} {{os_version_id}} netboot preseed install (works)
                KERNEL /{{os_id}}/{{os_version_id}}/netbootimages/linux
                APPEND initrd=/{{os_id}}/{{os_version_id}}/netbootimages/initrd.gz auto=true priority=critical netcfg/choose_interface=enp1s0f0 preseed/url=http://{{ dnsmasq_gateway }}:8080/sharedisos/{{os_id}}/{{os_version_id}}/conf/default/preseed.conf 

              LABEL {{os_id}} preseed install (not working)
                MENU LABEL Install {{os_id}} {{os_version_id}} preseed install (not working)
                KERNEL /{{os_id}}/{{os_version_id}}/bootimages/vmlinuz
                INITRD /{{os_id}}/{{os_version_id}}/bootimages/initrd.gz
                APPEND  root=/dev/nfs nfsroot={{ dnsmasq_gateway }}:/srv/nfs/{{os_id}}/{{os_version_id}},tcp,v3 ip=:::::enp1s0f0:dhcp rw  auto=true priority=critical netcfg/choose_interface=enp1s0f0 preseed/url=http://{{ dnsmasq_gateway }}:8080/sharedisos/{{os_id}}/{{os_version_id}}/conf/default/preseed.conf 
                
              LABEL {{os_id}} memdisk install ( no preseed )
                MENU LABEL Install {{os_id}} {{os_version_id}} memdisk install ( no preseed )
                KERNEL memdisk
                INITRD /{{os_id}}/{{os_version_id}}/isos/{{iso_name}}
                APPEND iso raw
              LABEL local
                MENU LABEL Boot from local disk
                LOCALBOOT 0
            mode: '0644'
            
#                SYSAPPEND 3
#                APPEND  url=http://{{ dnsmasq_gateway }}:8080/sharedisos//{{os_id}}/{{os_version_id}}/{{iso_name}} cloud-config-url=/dev/null autoinstall  ds=nocloud-net;s=http://{{ dnsmasq_gateway }}:8080/sharedisos//{{os_id}}/{{os_version_id}}/conf/default/ fsck.mode=skip
#                APPEND auto=true priority=critical netcfg/choose_interface=enp1s0f0 root=/dev/nfs nfsroot={{ dnsmasq_gateway }}:/srv/nfs/{{os_id}}/{{os_version_id}},tcp,v3 rw preseed/url=http://{{ dnsmasq_gateway }}:8080/sharedisos/{{os_id}}/{{os_version_id}}/conf/default/preseed.conf 


  vars:
      os_id: "{{hostvars[item].os_id | default('', true) | trim }}"
      os_version_id: "{{ hostvars[item].os_version_id | default('', true) | trim }}"
      iso_name: "{{ operating_systems | selectattr('os_id', 'search', os_id)  | selectattr('os_version_id', 'equalto', os_version_id) | map(attribute='iso_name') | first }}"
      iso_file_path: "{{sharedisos}}/{{os_id}}/{{os_version_id}}/{{iso_name}}"
      iso_mount_point : /tmp/iso/{{os_id}}/{{os_version_id}}

           
      