- name: Configure HP ProCurve 3400cl
  hosts: procurve_switches
  gather_facts: no

  tasks:
  - name: run show command
    ansible.netcommon.telnet:
      port: "{{ ansible_port | default(omit) }}"
      user: manager
      password: minad1234
      timeout: 10
      login_prompt: ""
      password_prompt: "Password: "
      prompts:
#      - 'ProCurve Switch 3400cl-48G# '
       - '[>#]'
      command:
      - show version
      - config
      - vlan 1
      - name "Default_IPMI_VLAN"
      - untagged 3,6,9,12,15,18,21,24,43 
      - ip address dhcp-bootp
      - exit
      - vlan 20
      - name "Secondary"
      - untagged  2,5,8,11,14,17,20,23,42  
      - exit
      - vlan 10
      - name "Production"
      - untagged 1,4,7,10,13,16,19,22,41
      - exit
      - write memory
      - exit
      - show running_config
      
    register: telnet_output

  - name: Display telnet output
    debug:
      var: telnet_output.stdout_lines
