---
ansible_connection: ssh 
ansible_user: ansible
ansible_ssh_pass: minad1234

nfs_exports:
     - path: /srv/nfs/debian
       clients: "*"
       options: "ro,sync,no_subtree_check,no_root_squash"

operating_systems:
     - os_id: "ubuntu"
       os_version_id: "26.04"
       iso_url: https://releases.ubuntu.com/resolute/ubuntu-26.04-live-server-amd64.iso
       iso_name: ubuntu-26.04-live-server-amd64.iso
       
     - os_id: "debian"
       os_version_id: "13.6.0"
       iso_url: https://cdimage.debian.org/debian-cd/13.6.0/amd64/iso-cd/debian-13.6.0-amd64-netinst.iso
       iso_name: debian-13.6.0-amd64-netinst.iso

     - os_id: "gparted"
       os_version_id: "1.8.1-6"
       iso_url: https://downloads.sourceforge.net/gparted/gparted-live-1.8.1-6-amd64.iso
       iso_name: gparted-live-1.8.1-6-amd64.iso
